### ISSUE TITLE
Show AST even when it contains errors

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas-tools#137]
It'd be very useful to see parsed trees that contain errors. Could the AST page show both errors and the tree, please?

**Comment by nojaf** [comment]
Initial attempt to show the errors looks like this:
![image](https://user-images.githubusercontent.com/2621499/107775835-21a9a580-6d41-11eb-92e9-02055c4fff94.png)

Will be deployed shortly.

**Comment by auduchinok** [comment]
@nojaf Thanks a lot! 🙂
