### ISSUE TITLE
does not install or instructions are inadequate

### ISSUE THREAD

**Issue by yetanotherlogonfail** [fsprojects/fantomas-tools#178]
C:\Users\carlr>dotnet tool install -g fantomas-tool

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.102

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
You can invoke the tool using the following command: fantomas
Tool 'fantomas-tool' (version '4.3.0') was successfully installed.

C:\Users\carlr>fantomas Tool ''fantomas-tool'
Input path is missing...

C:\Users\carlr>fantomas Tool 'fantomas-tool'
Input path is missing...

C:\Users\carlr>fantomas Tool
Input path is missing...

C:\Users\carlr>fantomas
Input path is missing...

C:\Users\carlr>Tool 'fantomas-tool'
'Tool' is not recognized as an internal or external command,
operable program or batch file.

what now ?

**Comment by nojaf** [comment]
Hello, this is the repository for the online tool.
Please report Fantomas related problems at https://github.com/fsprojects/fantomas.

Our docs mention that the command line executable name is `fantomas` (and not the NuGet package name `fantomas-tool`): https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#using-the-command-line-tool
You actually received this message in your terminal:
> You can invoke the tool using the following command: **fantomas**
