### ISSUE TITLE
The tool page missing content in Safari

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas-tools#2]
<img width="1436" alt="Screenshot 2020-05-19 at 22 56 06" src="https://user-images.githubusercontent.com/3923587/82372084-0022c400-9a24-11ea-984a-8a227370c509.png">

The old Fantomas online tool works fine (except for the red header that I'd prefer to be able to hide):
<img width="1436" alt="Screenshot 2020-05-19 at 22 57 58" src="https://user-images.githubusercontent.com/3923587/82372248-509a2180-9a24-11ea-9d6f-ead073b96d81.png">

**Comment by nojaf** [comment]
I suppose I can't convince you to use a different browser 😅?

**Comment by auduchinok** [comment]
Yeah, I'd prefer not _installing_ another browser to be honest. 😄

**Comment by 7sharp9** [comment]
Ive just found this too :-(

I can't use the Fantomas one as I want the AST output.

**Comment by 7sharp9** [comment]
The height of the Monaco element seems to be 5px so the data is there its just the window is really tiny to view it :-(

**Comment by auduchinok** [comment]
Good news is it seems to be fixed in Safari 14 beta. Though, it's probably early to close the issue yet. 🙂 
<img width="1436" alt="Screenshot 2020-07-23 at 21 12 10" src="https://user-images.githubusercontent.com/3923587/88322295-308b2500-cd29-11ea-86fc-15eb65a06cbf.png">

**Comment by JaggerJo** [comment]
Just discovered the same issue. 🙃 Firefox to the rescue!

**Comment by auduchinok** [comment]
Seems to get broken again in Safari 14 release. 😢

**Comment by nojaf** [comment]
Hey, so maybe, just maybe this problem was solved 😅.
I've updated to Fable 3 and may have changed some CSS along the way.
And this whole accident could have made the tool usable in Safari.
Or not, I don't know as I don't have a Mac.

**Comment by JaggerJo** [comment]
Just tested it and it's still broken on MacOS 11.1

**Comment by nojaf** [comment]
Dammit, ok worth a try I guess 🙈 .
So @JaggerJo cache cleared and all that jazz?

**Comment by JaggerJo** [comment]
@nojaf jap - it really seems like a bug in safari as adding a fixed value and then removing it fixes it.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/13090415/100158914-38143380-2ead-11eb-8e37-95ad00161a4c.png">

Commented out and still working

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/13090415/100159064-642fb480-2ead-11eb-8b73-70a8e863c6b8.png">

**Comment by auduchinok** [comment]
I've just noticed it finally works in Safari 14.1.1 release.
<img width="1436" alt="Screenshot 2021-06-17 at 21 04 50" src="https://user-images.githubusercontent.com/3923587/122450427-ac303900-cfaf-11eb-88ca-5773effe6089.png">

**Comment by nojaf** [comment]
Nice, I knew this would eventually solve itself 😅.
Thanks for the confirmation.
