### ISSUE TITLE
`Create an issue!` button is missing

### ISSUE THREAD

**Issue by Alkasai** [fsprojects/fantomas-tools#3]
The "report issue" button is missing in Edge (Chromium-based) browser.
![image](https://user-images.githubusercontent.com/161976/83875595-62a6e000-a705-11ea-8480-0b1064839b70.png)

Console error:
![image](https://user-images.githubusercontent.com/161976/83875605-65093a00-a705-11ea-935e-750f8bd0ba3f.png)

Browser version (Windows 10):
![image](https://user-images.githubusercontent.com/161976/83875645-794d3700-a705-11ea-99eb-c85c60c011de.png)

**Comment by Alkasai** [comment]
Oh I guess this is only visible on the Preview version.

**Comment by nojaf** [comment]
Oh we might have broken something there 😱.
It could be a regression, could you paste the link your are trying?

**Comment by Alkasai** [comment]
https://fsprojects.github.io/fantomas-tools/#/fantomas/latest?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPMAvGMGNAK4BOFiAdlgLIKLoA6FLNEX3PvA7gEssACzABlLLGrwxiAM5yBsGnMJgAFGw68duvfu4BbAIZZoo6uljH4YQSK2cDzlzoA%2BYLBTKIwAWgA%2BMDkVR1dw8I8AM2N0OV9A4JUwAAEkuQAFagA3MIj8-QAaUmUsARoyUyUaABVYAGtaMABKMABfSELwKHisMpoAczlUMABtbohQXkgAEiwATwAHZDRIcqxOia5Z7NifEfHdAAYu3UgASRokOjFF42hEADkyQ03dABYtiABdLbbTrhTHizBbLEZrOhvYEzXbofZoQ46ACMAOmGWMA0QAHUBPARFDeEiAExHL5gX7cf5bIHcEFLFZQABGsFg6AJ2xhewZiN4RNRwNkhgEcCsNAAglgAKJXADyUQAMuVkPzuDE4ogyRSuFTuDSOaCGZBmaz2RAdlyDmSIABmFXbW73RAAIUQUSkiDFFAGL1oGztEC8Pk1f35erNc3p4ONbLt5rh3KtYHe-qgDoeLrd1AAwqzlKauGr4sHKaGyXSwato-m4-CxomAKwpyBpj1RLCICg5wwmfMB7wa3haiA6wFliMVpksmNj2G1nk8ABsTZbGfdguFuZovbAhYHPCH7VL03Hhqrsc58ctugA7Mu7g8xW2O%2BuRXmU4G99wDyPJmODVGp2rC850TAAOJtLmuLAZVqCh5hxfEU13YttSPaF-0rQDz1nBNdAATibAAlRApCQCgZWWGgABFEGgdBjAoKo30TZDBxDak-0jTCTWwi0EUTJETkTZt7w9ChYDIK4aPQAQhXbChtw-FDhzQ2kTwAniZz4utdCRFFhIAaUQRBFkeRA%2BBkmhW3k7dWP3djdU4icIT9LTL343S%2BWE%2BhjFwc4ohqYRaEldUxGEKQsBxPFhG3d5STYksOOPDDJ0048cKvZFbWEiQKGFBgmFs2IiwS7Vum%2BAE1jkAAxRQRmQtogA

Also you'll see the latest doesn't format this correctly, but preview does.

```
let x = { currentModel
                    with StoredSessions = (
                                            match reload with
                                            | true -> sns
                                            | false -> sns @ snsPrev
                                            , continuationToken ) }
```

Formats as:
```
let x =
    { currentModel with
          StoredSessions =
              (match reload with
               | true -> sns
               | false -> sns @ snsPrev, continuationToken) }
```

But the intent is this:
```
let x =
    { currentModel with
          StoredSessions =
              ((match reload with
                | true -> sns
                | false -> sns @ snsPrev), continuationToken) }
```

**Comment by nojaf** [comment]
Ah sorry, I remember now that we indeed only allow the creation of bugs on the latest code.
This avoids the report of issues that are no longer a problem.
It is a relief though that the preview is able to format it correctly.

**Comment by Alkasai** [comment]
I would recommend calling it out that the bugs can be reported on Preview only. This should encourage people trying out the newer version, where hopefully it's already addressed, like in my case.

**Comment by nojaf** [comment]
Indeed, perhaps some extra text could make that clear.
