### ISSUE TITLE
Reformatting multiple array index operators (v6 style) adds spaces that are invalid

### ISSUE THREAD

**Issue by richardcox13** [fsprojects/fantomas-tools#353]
```fs
let a = Array.create 10 -1
let b = Array.create 10 a

printfn "%d -> %d" a[0] (b[0][0])
```

Reformat (running this from VS Code with Ionide-fsharp 5.11.0 running fantomas-tool 4.6.5) results in

```fs
let a = Array.create 10 -1
let b = Array.create 10 a

printfn "%d -> %d" a[0] (b [ 0 ] [ 0 ])
```

Which is not valid. Using `.[0]` does not have this problem.

**Comment by nojaf** [comment]
Please create an issue using the [online tool](https://fsprojects.github.io/fantomas-tools):

![image](https://user-images.githubusercontent.com/2621499/156924272-a87a3906-546d-400f-bc83-93c88bcdf359.png)

See [contribution guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by richardcox13** [comment]
Oops, missed this reply. See https://github.com/fsprojects/fantomas/issues/2151.

**Comment by nojaf** [comment]
Thank you! I'll get back to you over there.
