### ISSUE TITLE
In GitHub.io documentation, underscores in setting names are rendered as italic delimiters

### ISSUE THREAD

**Issue by LyndonGingerich** [fsprojects/fantomas-tools#405]
Section titles in https://fsprojects.github.io/fantomas/docs/Configuration.html appear to render `_foo_` as _foo_, in italics. Thus, for example, `fsharp_space_before_parameter` is rendered as "fsharp _space_ before_parameter" (though without spaces).

Weirder, the URL for that section is https://fsprojects.github.io/fantomas/docs/Configuration.html#fsharp-space-before_parameter. Notice the inconsistency of hyphens and underscores in the target anchor.

**Comment by nojaf** [comment]
Hello Lyndon,

The documentation is actually hosted on https://github.com/fsprojects/fantomas.
There we use [F# Formatting](https://fsprojects.github.io/FSharp.Formatting/) to generate the website.

The bug you are describing look like this one:
https://github.com/fsprojects/FSharp.Formatting/issues/389

I couldn't find a bug about the hyphens, feel free to report (and solve) it over at https://github.com/fsprojects/FSharp.Formatting.

**Comment by LyndonGingerich** [comment]
@nojaf Newbie mistake, sorry. Many thanks!
