### ISSUE TITLE
Error shows wrong range

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas-tools#497]
For this code:

```fsharp
{ Aa. }
```
There should an error with range (1,4-1,5) or something like that, but it's (0,0-0,0) instead.
<img width="1163" alt="Screenshot 2023-02-09 at 12 09 59" src="https://user-images.githubusercontent.com/3923587/217796725-338299df-9876-4abe-90b5-0e7a019af44a.png">

**Comment by nojaf** [comment]
This is either a visualization problem or something wrong with `Fantomas.FCS`.
In both cases: I'll be looking forward to your PR 😸

**Comment by nojaf** [comment]
This is now fixed.
