### ISSUE TITLE
Omit `tmp.fsx` in AST tab dump

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas-tools#498]
If we analyze ranges in the dump in #494, then it also becomes easy enough to remove `tmp.fsx` file names, so the dump is easier to look at and to reason about.

**Comment by nojaf** [comment]
I don't think #494 is all that related to this suggestion.
The removal of `tmp.fsx` seems more like a string replacement on the server.
While in #494 you need to respond to the cursor location in the editor.
I'm ok with this suggestion and will mark this up for grabs.

**Comment by nojaf** [comment]
This is now done after our latest sync.
