### ISSUE TITLE
Some ranges might be not highlighted in the AST tab

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas-tools#500]
@nojaf Thanks a lot for adding this highlighting in #499, it's super cool!

I've just tried it and found that in [this case](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQ2wAuYAHmAC8YAIyQQAXyA) the very last range isn't highlighted for some reason:

<img width="1216" alt="Screenshot 2023-02-13 at 13 48 43" src="https://user-images.githubusercontent.com/3923587/218461711-a0dea4d3-3b00-4378-9b31-082c9669df0a.png">

**Comment by nojaf** [comment]
It appears only to be working for the first range in that specific line.
Not sure what's up there.

**Comment by nojaf** [comment]
@auduchinok could you try that again (after clearing your browser cache)?
I think I fixed it.

**Comment by auduchinok** [comment]
Yup, it works now, fantastic!

**Comment by auduchinok** [comment]
Could you also remove an existing highlighting when clicking outside of a range?

**Comment by nojaf** [comment]
Should be ok now.
