### ISSUE TITLE
Remove usage of vis-react package

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas-tools#538]
Hi @jindraivanek,

I didn't catch this at the time of your PR, but in https://github.com/fsprojects/fantomas-tools/pull/478 you added [vis-react](https://www.npmjs.com/package/vis-react). This is a bit problematic as I noticed yesterday that the [source repository](https://github.com/anishmprasad/vis-react) does not contain the source code. And the project is most likely not really maintained if I go off of the repository activity.
It also is not using the well-maintained [vis-network](https://github.com/visjs/vis-network).

This will bite us most likely sooner than later, so I'd like to port the current code to use `vis-network` and create our own little React wrapper (to reduce the number of dependencies).
To reiterate: the goal is to shuffle some npm dependencies and keep all your great work in the tool!

I want to do the work myself and I mostly wanted to let you know that this is the plan.
And I have some questions about the current code:
- Why is a union range created for a node? I would expect each node to have a range that includes all its children. If you found examples where that is not the case, I would like to fix that on the parser (or ASTTransformer) side rather than here in this tool.

https://github.com/fsprojects/fantomas-tools/blob/b5c0ebd24248f3f5104b7ccf972772c3277d7bb7/src/client/fsharp/Oak/GraphView.fs#L83-L87

- When you click on a certain node, to drill into the children:
![image](https://user-images.githubusercontent.com/2621499/231379915-75ad78fa-18dd-4666-b6dd-c5ca3ab16bcb.png)

Is this logic purely in the tool? Not being processed inside that React component right?

**Comment by jindraivanek** [comment]
Hello, sorry for delay. 

To the questions:

> * Why is a union range created for a node? I would expect each node to have a range that includes all its children. If you found examples where that is not the case, I would like to fix that on the parser (or ASTTransformer) side rather than here in this tool.

I think I just kept this from old graph view that used FCS AST to be on safe side, we can just remove it.

> When you click on a certain node, to drill into the children:
> Is this logic purely in the tool? Not being processed inside that React component right?

Yes, there is callback for "node select", in it we change graph data in component, and component redraw itself.
