### ISSUE TITLE
Add before / after indicators for trivia in Oak view

### ISSUE THREAD

**Issue by majocha** [fsprojects/fantomas-tools#545]
I propose we add some indicators in the Oak view, showing whether the given trivia comes from `ContentBefore` or `ContentAfter`.

Something like this:
<img width="205" alt="image" src="https://user-images.githubusercontent.com/1760221/233022364-386ed12e-0006-493e-926f-11b98de39565.png">

Alternatively, maybe just highlight the parent node on hover over trivia?

**Comment by majocha** [comment]
> PS: do you know about [graph mode](https://fsprojects.github.io/fantomas-tools/#/oak?data=N4KABGBEDGD2AmBTSAuKAbRAXMBDMAvGImAPSkA6AThQHaY4BGhYjkANOFEgGYCWtRAGdUUDl0h8hAMSF9RPXOiGJOESUIDiVXAAcAFgDU%2BiAO6isVAK6IQAXyA)?

Oh, wow! Sweet! I missed this. That's something that should not be hidden in the settings. A little toggle button maybe?

**Comment by nojaf** [comment]
> A little toggle button maybe?

No, I don't think that is really necessary. Overall, this is nice and useful but I rarely use it, to be honest.

**Comment by nojaf** [comment]
I took this into account in https://github.com/fsprojects/fantomas-tools/pull/566
