### ISSUE TITLE
How do I keep my alignment?

### ISSUE THREAD

**Issue by WillEhrendreich** [fsprojects/fantomas-tools#601]
Hey guys, thanks for the awesome tool.

Hey, I am a weirdo, I'll admit it, but since I started using neovim use the [Mini.Align](https://github.com/echasnovski/mini.align) plugin, I've really started to enjoy how this style looks and how easy it is to do with that plugin.
![image](https://github.com/fsprojects/fantomas-tools/assets/55286472/4abba93c-115e-43b2-b009-7398d21c4764)

Obviously this isn't everyone's cup of tea, and I'm fine with that, in fact when I worked primarily in visual studio I'd see this sort of thing from time to time and hate it, my mind would reel at the nightmare it would be to maintain the alignment, not realizing the way they did it was likely with a tool so it wouldn't be manual.. 

Anyway, mostly I work on my codebases by myself, so .. I likes what I likes and it's my room so I like to decorate it with my stuff, you know? 

I'd really like to use fantomas too, there are a lot of other things I'd love to have done automatically, but I just don't want it to mangle my text alignment with regard to the delimiters I set. 

but when I format on save it does this.. 
![image](https://github.com/fsprojects/fantomas-tools/assets/55286472/53aa9567-4776-41aa-a190-e8eed2fd1abe)
Is it the end of the world? 
Well.. no.. I guess.. 

But I'm annoyed about it, and if it's easily toggled to not do this I thought I'd ask, because I didn't see it as something that could be configured. 

If not, I totally get it, maybe it's too much trouble than it's worth. But maybe it's something that can be as an option?

**Comment by dawedawe** [comment]
Hey @WillEhrendreich,
check out our configuration [docs](https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html)
```
MultilineBracketStyle = Stroustrup
IndentSize = 2
```
should get you somewhere.
You can play arount with these things in the [fantomas-tool](https://fsprojects.github.io/fantomas-tools/)

**Comment by WillEhrendreich** [comment]
Actually I got the bracket style and indent size, im talking about the alignments of the assignments of each field. I like them with the = all in a column. It makes column based multi-line editing very easy.

**Comment by dawedawe** [comment]
Sorry, we don't support that.
