### ISSUE TITLE
Disappearing static member name

### ISSUE THREAD

**Issue by johnpage-agixis** [fsprojects/fantomas-tools#81]
I have a bug that occurs in VS Code with the latest Ionide extension (v4.17.0), but I can't reproduce it in the fantomas online tool.
When I use the Format Document option in VS Code the following code gets slightly mangled
```fsharp
type CardValue =
    | Basic of int
    | Jack
    | Knight
    | Queen
    | King
    static member allWithKnight = 
        [ 
            for n in 1..10 do
                yield Basic n
            yield Jack
            yield Knight
            yield Queen
            yield King 
        ]
```
becomes
```fsharp
type CardValue =
    | Basic of int
    | Jack
    | Knight
    | Queen
    | King
    static member  =
        [
            for n in 1 .. 10 do
                yield Basic n
            yield Jack
            yield Knight
            yield Queen
            yield King
        ]
```
As you can see the name of the static member has disappeared.

I have tried copying this module and all those that depend on it into the fantomas online tool in order to test whether a future use of the static member might confuse fantomas, but the fantomas online tool never removes the static member's name.

**Comment by nojaf** [comment]
Hey @johnpage-agixis, thanks for the report. If you cannot reproduce this in the online tool that hints that it is already fixed.
I'll add a regression test just in case.

**Comment by nojaf** [comment]
Created https://github.com/fsprojects/fantomas/issues/1154
